### ISSUE TITLE
有个cmake的书可以看下，感觉你是做翻译的

### ISSUE THREAD

**Issue by lglgdouble** [xiaoweiChen/xiaoweiChen#1]
https://github.com/PacktPublishing/Modern-CMake-for-Cpp

https://www.amazon.cn/dp/B09MMK8CKN/ref=sr_1_6?__mk_zh_CN=%E4%BA%9A%E9%A9%AC%E9%80%8A%E7%BD%91%E7%AB%99&crid=1ABVL82QC1I60&keywords=c%2B%2B&qid=1652754065&sprefix=c+%2Caps%2C91&sr=8-6

**Comment by xiaoweiChen** [comment]
感谢关注哈。

其实我不是专业做翻译的，翻译只是一个兴趣爱好，想把自己看过的东西和其他人分享一下。

这本书我这边已经拿到电子版本了(免费)。

看了下其中内容会和[cmake cook book](https://github.com/xiaoweiChen/CMake-Cookbook) 和 [professional cmake](https://book.douban.com/review/13972546/) 重叠的比较多。要是着急学习CMake这两本书可以作为入门和进阶使用。

这本书翻译的话，可能会放在后面了。
