### ISSUE TITLE
请你翻译一下C++20 - The Complete Guide，谢谢

### ISSUE THREAD

**Issue by CruiseYoung** [xiaoweiChen/xiaoweiChen#2]
书籍（最新版）
pdf下载地址：https://breathebook.co/d/8907 
epub下载地址：https://breathebook.co/d/8804
如果下载不到，请留下你的邮箱，我可以发给你。

**Comment by xiaoweiChen** [comment]
哈哈，你是第二个给我提及这本书的。
这本书我这边有得，只是还没安排上。
下一本是关于 元编程 的，之后就是这本了。估计在年中前应该能翻出来。

**Comment by CruiseYoung** [comment]
那先感谢了，我发的这个版本是This version was published on 2022-10-30的，也是最新的(可以看看你的版本是否是最新的)

**Comment by xiaoweiChen** [comment]
我本地的版本是2021-12-31的，的确你的会更新一些。

**Comment by CruiseYoung** [comment]
建议你翻译[leanpub](https://leanpub.com/)这种类似平台出版的有日期节点的著作，可以在首页写出版本日期，再留下你的联系邮箱，这样大家手里有新的就会主动提供给你，也方便和你直接交流和沟通。

**Comment by xiaoweiChen** [comment]
嗯，日期这个可以加在pdf的正文中。

不过，个人觉得没必要使用邮箱或者其他即时聊天工具进行沟通。有什么想法和建议可以在github或豆瓣给我留言，这两个地方我经常逛的，应该会及时看到。

因为我翻译的书也仅是个人学习和爱好，并不是专职来做这件事情的。所以每本书有从我开放阅读后，会有6个月的维护期，并不会长期维护。若这个时间过了，该书就不再进行维护了。若是有人想要继续更新，可以fork过去进行更长期的维护。

若是在维护期内，书有更新，可以直接提PR进行更新。提交PR的时候可以留下新版本的下载地址，或者对译版进行自行维护也是可以的。

**Comment by xiaoweiChen** [comment]
https://github.com/yihong0618/bilingual_book_maker

可以尝试使用ChartGPT可以进行翻译，刚好这个自动翻译可以直接接受epub作为输入

**Comment by CruiseYoung** [comment]
我去OpenAI注册，提示注册不了

**Comment by xiaoweiChen** [comment]
是手机注册那里过不去是么？用虚拟手机号是可以的，不过要花几块钱。
我这边已经注册好了，后续会尝试一下，看看翻译出来的效果怎么样。

**Comment by xiaoweiChen** [comment]
```
# 使用彩云小译翻译(彩云api目前只支持: 简体中文 <-> 英文， 简体中文 <-> 日语)
# 彩云提供了测试token（3975l6lr5pcbvidl6jl2）
# 你可以参考这个教程申请自己的token (https://bobtranslate.com/service/translate/caiyun.html)
python3 make_book.py --model caiyun --caiyun_key 3975l6lr5pcbvidl6jl2 --book_name test_books/animal_farm.epub
```

你那边要是不想花钱注册OpenAI可以试试彩云的翻译，不知道需不需要科学上网

使用OpenAI的话，需要科学上网，我这边已经开始用OpenAI提供的Key进行翻译了

**Comment by CruiseYoung** [comment]
花钱能注册也可以，如你有花钱注册的教程，帮忙分享一下。我也去搜一下。彩云小译翻译我也去试一下。方便以后阅读英文文档时参考

**Comment by xiaoweiChen** [comment]
一文教你快速注册OpenAi
https://cloud.tencent.com/developer/article/2190154
