### ISSUE TITLE
非常感谢

### ISSUE THREAD

**Issue by emodiliugan** [xiaoweiChen/xiaoweiChen#3]
非常感谢给我们带来这么多好书

**Comment by xiaoweiChen** [comment]
我的译本能够帮助到你，我也很高兴。
若有感觉不错的英文原版书籍，可以推荐给我。

**Comment by emodiliugan** [comment]
如果您有时间，有本很不错的书叫embracing_modern_c++_safely

**Comment by xiaoweiChen** [comment]
这本书我有原版的，但页数太多了

**Comment by emodiliugan** [comment]
感觉C++现在遇到安全问题质疑，这本书真的很及时
