### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by sweet2honey** [xiaoweiChen/xiaoweiChen#4]
关注好一段时间了。
最近也在啃 C++ 20 Complete Guide 和 TMP with C++。虽然自己英文还 ok，但是能找到有译本可以对照理解学习实在是太好啦。
然后再点开 repo，全是看过、准备看的书，好开心。

学习的路上遇到你，感谢感谢~

**Comment by xiaoweiChen** [comment]
很高兴看到我的翻译书籍，对你的学习有所帮助 ：）
若有感觉不错的英文原版书籍，可以推荐给我一起学习，我这边也会考虑译出来分享给大家。
